version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fastapi_network

  app:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - fastapi_network
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  fastapi_network:

volumes:
  mysql_data:
